version: '3'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    command: npm run start
    volumes: 
      # Mount the host path, ., to the path "/usr/src/app" in the docker container.
      # Do this so that nodemon can watch for file changes and restart within the container.
      # Should move to a src folder.
      - .:/usr/src/app
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    # Can use env_file with a '-', or can use 'environment' with no dash and specify the username and password directly
    env_file:
      - .database-env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data: